# Generated by Django 3.2 on 2021-12-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_upvote_downvote_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='', max_length=20),
        ),
    ]
